<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DbBrowser</RootNamespace>
    <AssemblyName>DbBrowser</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="App_Data\apg.xml" />
    <Content Include="App_Data\bestiary.xml" />
    <Content Include="App_Data\bestiary2.xml" />
    <Content Include="App_Data\bestiary3.xml" />
    <Content Include="App_Data\pfrpg.xml" />
    <Content Include="App_Data\uc.xml" />
    <Content Include="App_Data\um.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PathfinderDb.Schema" Version="1.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
</Project>